SPOTIPY_CLIENT_ID = 'SPOTIPY_CLIENT_ID'
SPOTIPY_CLIENT_SECRET = 'SPOTIPY_CLIENT_SECRET'
SPOTIPY_REDIRECT_URI = 'SPOTIPY_REDIRECT_URI'
YA_TOKEN = "YA_TOKEN"
PLAYLIST_ID = 'PLAYLIST_ID'
PROXIES = {
    'https': 'PROXIE'
}
